CMSIS_MCU = RA6M3
MCU_SERIES = m4
LD_FILES = boards/VK_RA6M3/vk_ra6m3.ld

# MicroPython settings
MICROPY_VFS_FAT = 1
MICROPY_PY_LWIP = 1
MICROPY_PY_SSL = 1
MICROPY_SSL_MBEDTLS = 1

# FSP settings
USE_FSP_QSPI = 1
USE_FSP_SDHI = 1
USE_FSP_ETH = 1
USE_FSP_SCE = 1
USE_FSP_LCD = 1
USE_FSP_CAM = 1
#USE_FSP_CAN = 0

CFLAGS+=-DDEFAULT_DBG_CH=9

# module settings

#CAMERA_MOD_DIR := $(USERMOD_DIR)
SRC_USERMOD_C += modlcd.c
#CFLAGS_USERMOD += -I$(CAMERA_MOD_DIR) -DMODULE_CAMERA_ENABLED=1